<div class="mt-2 col-md-10 offset-md-1" style="min-height: 100%;position:relative;" id="body-cont-print">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <!-- deyisen yer-->
            <div class="shadow-p">
                <div class="text-right" style="    padding: 10px 10px;">
                    <h6 style="background-image: url(https://www.sdf.gov.az/development/img/widget-bg.png);background-repeat: repeat-x;background-position: bottom left;padding: 8px 0 23px;position: relative;"><a href="https://www.sdf.gov.az/az//generic/menu/Detail/177/menu" style="    color: #656565;"><span class="glyphicon glyphicon-align-right" aria-hidden="true" style="    font-size: 12px;"></span> Analitik informasiya</a></h6>
                </div>

                <!--<div class=" text-center">

                    <h3> Analitik informasiya</h3>
                </div>-->
                <div class="" style=" padding: 10px 16px;min-height:460px;">
                    <p>
                    </p><h3 style="text-align: center;" align="center"><span style="color: #003366;">ANALİTİK İNFORMASİYA</span></h3>
                    <hr>
                    <h3 style="text-align: center;" align="center">&nbsp;</h3>
                    <h4><span style="color: #003366;"><a href="../development/uploads/analitik_informasiya/amea_yaranma_tarixi.pdf" target="_blank"><span style="color: #003366;">Azərbaycan Milli Elmlər Akademiyası</span></a></span></h4>
                    <hr>
                    <h4><a href="../development/uploads/analitik_informasiya/tehsilde_elm.pdf" target="_blank"><span style="color: #003366;">Təhsildə elm</span></a></h4>
                    <hr>
                    <h4><span style="color: #003366;"><a href="../development/uploads/analitik_informasiya/elmi-pedaqoji_kadrlarin_hazirlanmasi.pdf" target="_blank"><span style="color: #003366;">Azərbaycan Respublikasının Təhsil Nazirliyi sistemində elmi-pedaqoji kadrların hazırlanması</span></a></span></h4>
                    <hr>
                    <h4><span style="color: #003366;"><a href="http://edu.gov.az/az/page/278" target="_blank"><span style="color: #003366;">Azərbaycan Respublikasının Təhsil Nazirliyi sistemində elmin inkişafı ilə bağlı sənədlər</span></a></span></h4>
                    <ul style="list-style-type: circle;">
                        <li style="display: inline !important;"></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/12197" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XX Respublika elmi konfransının keçirilməsi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/12139" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Təhsil Nazirliyi sistemində fəaliyyət göstərən ali təhsil müəssisələrində 2016-cı ildə keçiriləcək beynəlxalq və respublika səviyyəli elmi konfrans və simpoziumların siyahısının təsdiqi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/12133" target="_blank"><span style="color: #003366;">“Sabahın alimləri” V Respublika Müsabiqəsinin yekunları haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/11906" target="_blank"><span style="color: #003366;">Doktorantlara, ali təhsil, orta ixtisas və ilk peşə-ixtisas təhsili müəssisələrinin tələbələri və şagirdləri üçün müəyyən edilmiş təqaüdlərin artırılması haqqında Azərbaycan Respublikası Prezidentinin Sərəncamı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/11466" target="_blank"><span style="color: #003366;">“Sabahın alimləri” V Respublika müsabiqəsinin keçirilməsi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=10064" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XIX Respublika elmi konfransının keçirilməsi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=8819" target="_blank"><span style="color: #003366;">“Ali təhsil müəssisində təhsilalanların elmi tədqiqat işinin təşkili haqqında Əsasnamə”nin və “Tələbə Elmi Cəmiyyəti haqqına Nümunəvi Əsasnamə”nin təsdiq edilməsi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/8363" target="_blank"><span style="color: #003366;">Azərbaycan Respublikasında işçilərin attestasiyasının keçirilməsi Qaydalarının təsdiq edilməsi barədə Azərbaycan Respublikasının Nazirlər Kabineti Qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=8221" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Təhsil Nazirliyi sistemində fəaliyyət göstərən ali təhsil müəssisələrində 2014-cü ildə keçiriləcək beynəlxalq və respublika səviyyəli elmi konfrans və simpoziumların siyahısının təsdiqi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=8073" target="_blank"><span style="color: #003366;">“Sabahın alimləri” III Respublika Müsabiqəsinin yekunları haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=7812" target="_blank"><span style="color: #003366;">Təhsil Nazirliyinin vahid informasiya siyasətinin təmin olunması barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=7491" target="_blank"><span style="color: #003366;">"Azərbaycan Respublikasında təhsilin inkişafı üzrə Dövlət Strategiyası"nın təsdiq edilməsi haqqında Azərbaycan Respublikası Prezidentinin Sərəncamı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=7405" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XVIII Respublika elmi konfransının keçirilməsi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=7192" target="_blank"><span style="color: #003366;">Tədbirlər Planının təsdiqi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=7024" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Nazirlər Kabinetinin 2010-cu il 14 dekabr tarixli 235 nömrəli qərarı ilə təsdiq edilmiş "Doktoranturalar yaradılan Azərbaycan Respublikasının ali təhsil müəssisələrinin və elmi təşkilatların Siyahısı"nda dəyişikliklər edilməsi haqqında Azərbaycan Respublikası Nazirlər Kabinetinin Qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=7022" target="_blank"><span style="color: #003366;">"Azərbaycan Respublikasında elm işçilərin attestasiyasının keçirilməsi Qaydaları"nın təsdiq edilməsi haqqında Azərbaycan Respublikası Nazirlər Kabinetinin Qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="text-align: justify; color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=276&amp;id=6605" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Təhsil Nazirliyinin sifarişi əsasında 2013-cü ildə Təhsil Problemləri İnstitutunda yerinə yetiriləcək tədqiqat mövzularının siyahısının təsdiq edilməsi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=6602" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Təhsil Nazirliyi sistemində fəaliyyət göstərən ali təhsil müəssisələrində 2013-cü ildə keçiriləcək beynəlxalq və respublika səviyyəli elmi konfrans və simpoziumların siyahısının təsdiqi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=6400" target="_blank"><span style="color: #003366;">“Sabahın alimləri” II Respublika müsabiqəsinin yekunları haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://www.edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=5892" target="_blank"><span style="color: #003366;">Həsən bəy Zərdabinin 170 illik yubileyinin keçirilməsi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/view.php?lang=az&amp;menu=278&amp;id=5888" target="_blank"><span style="color: #003366;">“Sabahın alimləri” II Respublika Müsabiqəsinin keçirilməsi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5641" target="_blank"><span style="color: #003366;">Tələbələrin XVII Respublika fənn olimpiadasının yekunları barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5609" target="_blank"><span style="color: #003366;">Məmməd Səid Ordubadinin 140 illik yubileyinin keçirilməsi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5600" target="_blank"><span style="color: #003366;">Tədbirlər planının təsdiq edilməsi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5503" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XVII Respublika elmi konfransının keçirilməsi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/upload/file/emr-no641-23.04.12.pdf" target="_blank"><span style="color: #003366;">"Ali təhsilin doktorantura səviyyəsi üzrə ixtisasların Təsnifatı"nın təsdiq edilməsi haqqında Azərbaycan Respublikası Nazirlər Kabinetinin 15 mart 2012-ci il tarixli, 65 nömrəli qərarının elan olunması və icrası barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5391" target="_blank"><span style="color: #003366;">Elmi-Metotik Şuranın strukturunun, Rəyasət Heyəti və bölmələrin tərkibinin təsdiqi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5256" target="_blank"><span style="color: #003366;">“Sabahın alimləri” Respublika Müsabiqəsinin yekunları haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5135" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XVI Respublika elmi konfransının yekunları barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5057" target="_blank"><span style="color: #003366;">Ziya Bünyadovun 90 illik yubileyinin keçirilməsi haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/5051" target="_blank"><span style="color: #003366;">Azərbaycan xalqının ümummilli lideri Heydər Əliyevin anadan olmasının 89-cu ildönümü münasibətilə təhsil müəssisələrində keçiriləcək tədbirlər haqqında Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/4461" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Nazirlər Kabinetinin 7.09.2011-ci il tarixli, 143 nömrəli qərarının icrası barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/4460" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Nazirlər Kabinetinin 2010-cu il 14 dekabr tarixli 235 nömrəli qərarı ilə təsdiq edilmiş "Doktoranturalar yaradılan Azərbaycan Respublikasının ali təhsil müəssisələrinin və elmi təşkilatların Siyahısı"nda dəyişikliklər edilməsi haqqında Azərbaycan Respublikasının Nazirlər Kabinetinin qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/3834" target="_blank"><span style="color: #003366;">“Doktorantların və gənc tədqiqatçıların Respublika elmi konfransının Əsasnaməsi” nin təsdiqi barədə Azərbaycan Respublikasının təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/3832" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XVI Respublika elmi konfransının keçirilməsi barədə Azərbaycan Respublikasının təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/3784" target="_blank"><span style="color: #003366;">Ali məktəb tələbələrinin XVI Respublika fənn olimpiadası barədə qərar və əmr</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/3489" target="_blank"><span style="color: #003366;">“Dissertasiya işlərinə opponentliyə görə əməyin ödənilməsi haqqında” Azərbaycan Respublikası Nazirlər Kabinetinin 2 fevral 2011-ci il tarixli, 22 nömrəli qərarının elan olunması və icrası barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/2988" target="_blank"><span style="color: #003366;">"Doktoranturalar yaradılan Azərbaycan Respublikasının ali təhsil müəssisələrinin və elmi təşkilatların Siyahısı"nın təsdiq edilməsi haqqında Azərbaycan Respublikasının Nazirlər Kabinetinin Qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/2946" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Nazirlər Kabinetinin bəzi qərarlarına əlavələr edilməsi barədə Azərbaycan Respublikasının Nazirlər Kabinetinin Qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/2177" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Nazirlər Kabinetinin 2010-cu il 01 iyul tarixli 129 nömrəli qərarı ilə təsdiq olunmuş “ Doktoranturaların yaradılması və doktoranturaya qəbul Qaydaları“nın icrası ilə əlaqədar Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/2175" target="_blank"><span style="color: #003366;">Doktoranturaların yaradılması və doktoranturaya qəbul qaydaları</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/2133" target="_blank"><span style="color: #003366;">Ali məktəb tələbələrinin XV Respublika fənn olimpiadasının yekunları barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/1595" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XV Respublika elmi konfransının keçirilməsi barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/1594" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XV respublika elmi konfransına təqdim ediləcək elmi-tədqiqat işlərinin tərtib olunma Qaydaları</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/1561" target="_blank"><span style="color: #003366;">Doktorantların və gənc tədqiqatçıların XIV Respublika elmi konfransının yekunları barədə Azərbaycan Respublikası təhsil nazirinin əmri</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/1550" target="_blank"><span style="color: #003366;">Ali məktəb tələbələrinin XV Respublika fənn olimpiadasının qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/504" target="_blank"><span style="color: #003366;">Azərbaycan Respublikası Prezidentinin 4 may 2009-cu il tarixli 255 nömrəli sərəncamı ilə təsdiq edilmiş «Azəbaycan Respublikasında 2009-2015-ci illərdə elmin inkişafı üzrə Milli Strategiyanın həyata keçirilməsi üzrə Dövlət Proqramı»nda nəzərdə tutulan tədbirlərin həyata keçirilməsi üzrə Təhsil Nazirliyinin fəaliyyət planı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/upload/file/elm-senedler-01-06-09.pdf" target="_blank"><span style="color: #003366;">Azərbaycan Respublikasında 2009-2015-ci illərdə elmin inkişafı üzrə Milli Strategiya</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/500" target="_blank"><span style="color: #003366;">Ali məktəblərdə elmi-tədqiqat işlərinin təşkili və planlaşdırılması haqqında əsasnamə</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/498" target="_blank"><span style="color: #003366;">Ali məktəb tələbələrinin XIV Respublika fənn olimpiadasının qərarı</span></a></span></li>
                        <li style="text-align: left;"><span style="color: #003366;"><a style="text-align: justify;" href="http://edu.gov.az/az/page/278/497" target="_blank"><span style="color: #003366;">Ali məktəb tələbələrinin XIII Respublika fənn olimpiadasının qərarı</span></a></span></li>
                    </ul>
                    <p style="text-align: justify;"><span style="color: #003366;">&nbsp;</span></p>                        <p></p>

                </div>
                <div id="social" style="padding: 4px;"><a href="https://www.facebook.com/sharer/sharer.php?u=https://www.sdf.gov.az/az//generic/menu/Detail/177/menu" target="_blank" style="margin-right:5px;"><img src="https://www.sdf.gov.az/development/img/icon/fb.jpg"></a><a href="https://twitter.com/intent/tweet?url=https://www.sdf.gov.az/az//generic/menu/Detail/177/menu" target="_blank" style="margin-right:5px;"><img src="https://www.sdf.gov.az/development/img/icon/tw.jpg"></a><a href="mailto:?subject=Analitik informasiya&amp;body=https://www.sdf.gov.az/az//generic/menu/Detail/177/menu" style="margin-right:5px;"><img src="https://www.sdf.gov.az/development/img/icon/em.jpg"></a><a onclick="window.print()"><img src="https://www.sdf.gov.az/development/img/icon/pr.jpg"></a></div>
            </div>
            <div style="clear-both:"></div>
        </div>
    </div>
</div>