<div class="mt-2 col-md-10 offset-md-1" style="min-height: 100%;position:relative;" id="body-cont-print">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <!-- deyisen yer-->
            <div class="shadow-p">
                <div class="text-right" style="    padding: 10px 10px;">
                    <h6 style="background-image: url(https://www.sdf.gov.az/development/img/widget-bg.png);background-repeat: repeat-x;background-position: bottom left;padding: 8px 0 23px;position: relative;"><a href="https://www.sdf.gov.az/az//generic/menu/Detail/100/menu" style="    color: #656565;"><span class="glyphicon glyphicon-align-right" aria-hidden="true" style="    font-size: 12px;"></span> Yaranma tarixi</a></h6>
                </div>

                <!--<div class=" text-center">

                    <h3> Yaranma tarixi</h3>
                </div>-->
                <div class="" style=" padding: 10px 16px;min-height:460px;">
                    <p>
                    </p><h3 style="text-align: center;"><span style="color: #003366;">YARANMA TARİXİ</span></h3>
                    <hr>
                    <p style="text-align: justify;"><span style="color: #003366;">Elm dövlətin davamlı sosial-iqtisadi və mədəni inkişafını təmin edən mühüm amillərdən biridir. Müasir dövrdə dayanıqlı inkişafın əsasında elmi-texniki tərəqqinin rolunu və əhəmiyyətini ciddi bir faktor kimi qəbul edən Azərbaycan Respublikasının Prezidenti cənab İlham Əliyev son illər ölkəmizdə elmin inkişafı, elmi-texniki potensialın qorunub saxlanılması və modernləşdirilməsi, elm və təhsil sahəsində yüksək ixtisaslı kadrların hazırlanması, onlara daim qayğı göstərilməsi, cəmiyyətdə alimlərin, elm və təhsil işçilərinin nüfuzunun artırılması və Azərbaycanda alınmış elmi nəticələrin xaricdə tanıdılması sahəsində bir sıra mühüm qərarlar qəbul etmişdir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Elmin inkişafına dövlət səviyyəsində qayğı, əslində dövlətçiliyin möhkəmləndirilməsi və xalqın milli-mədəni tərəqqisinə və rifah halının yüksəldilməsinə xidmət edən siyasətin tərkib hissəsi kimi qiymətləndirilməlidir. Qloballaşma prosesinin dünyanı əhatə etdiyi və elmi-texniki tərəqqinin kifayət qədər yüksək sürətlə aparıldığı müasir dövrdə müstəqil Azərbaycan dövlətinin inkişafı elmi durumun səviyyəsindən və qazanılan nailiyyətlərin tətbiqindən əhəmiyyətli dərəcədə asılıdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">2011-ci il aprelin 26-da AMEA-nın illik ümumi yığıncağında iştirak edən Prezident İlham Əliyev vurğulayıb ki, müasir dövlətin qurulması, ölkənin tərəqqisi elmin inkişafı olmadan mümkün deyildir. Elmi tədqiqatların ölkədə aparılan iqtisadi siyasətlə bağlılığının diqqətdə saxlanılması vacib şərtdir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Ölkə başçısı son illərdə elmin inkişafına, bu sahədə problemlərin kompleks həllinə xidmət edən bir çox sərəncam və fərmanlar imzalamış, dövlət proqramları təsdiq etmişdir. Prezident İlham Əliyevin 2009-cu il 4 may tarixli "Azərbaycan Respublikasında 2009-2015-ci illərdə elmin inkişafı üzrə Milli Strategiya"nın və "Azərbaycan Respublikasında 2009-2015-ci illərdə elmin inkişafı üzrə Milli Strategiyanın həyata keçirilməsi ilə bağlı Dövlət Proqramı"nın təsdiq edilməsi haqqında", 2009-cu il 22 may tarixli "2009-2013-cü illərdə Azərbaycan Respublikasının ali təhsil sistemində islahatlar üzrə Dövlət Proqramı"nın təsdiq edilməsi haqqında" sərəncamları bu baxımdan xüsusi vurğulanmalıdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Milli Strategiya Azərbaycanın elmi-texniki potensialının, innovasiya siyasətinin, kadr hazırlığının imkanlarına əsaslanır, ixtisaslaşdırılmış elmi-tədqiqat institutlarının, həm də ayrı-ayrı istiqamətlər üzrə dövlət siyasətinə cavabdeh olan rəsmi strukturların qarşısına təxirəsalınmaz tələblər qoyur.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Son illərdə gənclər siyasətinə xüsusi diqqət yetirilir. Göstərilir ki, Azərbaycan gəncləri daim dövlətin diqqət mərkəzindədir. Gənclərin hərtərəfli inkişafı ölkənin sosial-iqtisadi, elmi və mədəni tərəqqisi ilə sıx əlaqədədir. Dövlət gənclər siyasəti - yeni nəslin öz bilik və bacarıqlarının, təbii potensialının effektli reallaşdırılmasını, cəmiyyətdə layiqli yer tutmasını təmin edən şəraitin yaradılması məqsədilə dövlət tərəfindən müəyyən edilmiş prioritetlər və həyata keçirilən tədbirlər sistemidir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Azərbaycan gənclərinin cəmiyyətin inkişafında və bu istiqamətdə qarşıya çıxan problemlərin həllində rolunu artırmaq, ölkənin gələcək inkişafında iştirakını və məsuliyyətini yüksəltmək, həmçinin beynəlxalq aləmə inteqrasiyasını sürətləndirmək dövlətin qarşıya qoyduğu əsas vəzifələrdəndir.</span></p>
                    <table>
                        <tbody>
                        <tr>
                            <td style="width: 260px; height: 190px;"><span style="color: #003366;"><img src="https://www.sdf.gov.az/development/uploads/ilham_aliyev_serencam.jpg" alt="ilham_aliyev_serencam" width="250" height="180"></span></td>
                            <td style="text-align: justify;"><span style="color: #003366;">Azərbaycan Respublikasının Prezidenti İlham Əliyevin 7 iyul 2011-ci il tarixli sərəncamı ilə təsdiq edilmiş "Azərbaycan gəncliyi 2011-2015-ci illərdə" Dövlət Proqramı respublikamızda dövlət gənclər siyasətinin formalaşdırılması istiqamətində irəliyə doğru atılan daha bir addım olmuşdur.</span></td>
                        </tr>
                        </tbody>
                    </table>
                    <p style="text-align: justify;"><span style="color: #003366;">Son dövrdə elmin inkişafı istiqamətində görülən ən mühüm işlərdən biri də Prezident İlham Əliyevin 2009-cu il 21 oktyabr tarixli sərəncamı ilə Azərbaycan Respublikasının Prezidenti yanında Elmin İnkişafı Fondunun yaradılmasıdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fondun təşkilində məqsəd ölkədə elmi-texniki potensialın qorunması, iqtisadiyyatın inkişafında bu potensialdan səmərəli istifadə edilməsi, mühüm sosial problemlərin həllində elm və texnikanın rolunun yüksəldilməsi, Azərbaycan Respublikasında elmi təşkilatlar, təhsil müəssisələri, digər müvafiq qurumlar və fiziki şəxslər tərəfindən təqdim olunmuş təbiət, texniki, humanitar və ictimai elmlər sahəsində dövlət və cəmiyyət üçün əhəmiyyət kəsb edən fundamental, tətbiqi və axtarış-innovasiya xarakterli elmi-tədqiqatların, proqramların, layihələrin və digər elmi tədbirlərin maliyyələşdirilməsi, alimlərin elmi fəaliyyətinin stimullaşdırılması və onlara əlavə yaradıcılıq imkanının yaradılmasıdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Dövlətin elmi informasiya və innovasiya ehtiyatlarının artırılması, ölkənin təbii resurslarının, mədəni və tarixi irsinin öyrənilməsinin gücləndirilməsi, aparılan araşdırmaların səmərəliliyinin artırılması və dünya elm məkanında Azərbaycanın layiqincə təmsil olunmasının təmin edilməsi, elmi-tədqiqatlar sahəsində fəaliyyət göstərən xarici və beynəlxalq təşkilatlarla əlaqələrin genişləndirilməsi, xarici təcrübənin öyrənilməsi və tətbiqi ilə bağlı tədbirlərin görülməsi, respublikada və xarici ölkələrdə müvafiq funksiyaları yerinə yetirən dövlət qurumları, qeyri-hökumət və digər təşkilatlarla əməkdaşlığın qurulması, elmi informasiya mübadiləsinin aparılması, lazım gəldikdə birgə elmi-tədqiqat layihələrinin yerinə yetirilməsi, həmçinin elmin kütləviləşdirilməsi istiqamətində müvafiq tədbirlərin həyata keçirilməsi və s. Elmin İnkişafı Fondunun qarşısına qoyulan vəzifələrdəndir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fond fəaliyyətə başladığı ilk gündən etibarən qrant müsabiqələri yolu ilə ölkədə elmin inkişafını çevik şəkildə dəstəkləmək, Azərbaycanda əldə olunan elmi nəticələri ölkə hüdudlarından kənarda tanıtmaq, elmi təşkilat və qurumlarda müxtəlif tədqiqatlarla bağlı maddi-texniki bazanı ən müasir səviyyədə yeniləmək və ya gücləndirmək, eyni zamanda, kadr hazırlığına xüsusi diqqət yetirmək, müxtəlif elmi tədbirlər keçirmək, alimlərin xaricə elmi tədbirlərə göndərilməsini, qısamüddətli təcrübəartırmada iştirakını təmin etmək, elmi nəşrləri dəstəkləmək və başqa bu kimi məsələlərin həllini bir məqsəd kimi müəyyənləşdirmişdir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Qurumun şəffaflıq prinsipləri üzərində təşkil edilmiş fəaliyyəti rəsmi internet səhifəsində (</span><span style="color: #003366;"><a href="http://www.sdf.gov.az" target="_blank"><span style="text-decoration: underline; color: #003366;">www.sdf.gov.az</span></a></span><span style="color: #003366;">) yerləşdirilmişdir və məlumatlar daim yenilənir. Müsabiqəyə daxil olmuş bütün layihələr yerli və lazım gəldikdə, xarici müstəqil elmi ekspertlərin iştirakı ilə və konfidensiallıq şərti qorunmaqla elmi ekspertizadan keçirilir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fond beynəlxalq əlaqələrə də xüsusi diqqət yetirir. Bu iş bir tərəfdən, cihazların alınması üçün keyfiyyətli məhsullar istehsal edən şirkətlərlə münasibətlərin qurulması və digər tərəfdən, beynəlxalq qrant müsabiqələrinin keçirilməsi üzrə əməkdaşlıq formalarında reallaşdırılır. Beynəlxalq qrant müsabiqələri üzrə əməkdaşlıq sahəsində ilk addım artıq atılıb və kifayət qədər uğurlu olub. Avropa Komissiyasının Tədqiqat və Texnoloji İnkişaf üzrə 7-ci Çərçivə Proqramı (FP-7) hüdudlarında Genişləndirilmiş Qara Dəniz Regionunda birgə elmi-tədqiqat layihələrinin həyata keçirilməsi üzrə müştərək pilot qrant müsabiqəsi (BS-ERA.NET) çağırışına Elmin İnkişafı Fondu da qoşulmuş, Azərbaycan alimləri 8 layihədə (2 layihədə koordinator olmaqla) iştirak etmişdir. 11 ölkədən olan 55 layihə sırasından 11 layihə qalib olmuşdur. Bu müsabiqədə Azərbaycandan olan bir layihə (koordinator qismində) də fərqlənmiş və qalib olmuşdur (ümumi statistika: Almaniya-2, Azərbaycan-1, Bolqarıstan-1, Rumıniya-4, Yunanıstan-3). Layihə Elmin İnkişafı Fondu və&nbsp;</span><span style="color: #003366;">İNTAS proqramı tərəfindən müştərək şəkildə maliyyələşdiriləcəkdir. Həmin layihə üzrə Azərbaycan alimlərinin Türkiyə, Gürcüstan və almaniyalı həmkarları ilə əməkdaşlığı nəzərdə tutulub.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fond ilə Fransa Milli Elmi Tədqiqatlar Mərkəzi (CNRS) və Belarus Respublika Fundamental Tədqiqatlar Fondu ilə birgə qrant müsabiqələri elan edilməsi sahəsində əməkdaşlıq haqqında memorandum və niyyət protokolu imzalanmışdır. 2012-ci ilin yarısından başlayaraq bu əməkdaşlığa start veriləcəkdir. Növbəti addım kimi Cənubi Koreya, yaxın qonşu ölkələrdən Gürcüstan və Rusiya ilə də əməkdaşlıq qurmaq planlaşdırılır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Elmin İnkişafı Fondu ilk qrant layihələri müsabiqəsini 2010-cu il iyunun 30-da&nbsp; elan etmişdir. Həmin dövrdən bu vaxta qədər 5 qrant müsabiqəsi (biri beynəlxalq və biri isə Gənc alim və mütəxəssislərin qrant müsabiqəsi olmaqla) keçirilmiş, 2 müsabiqənin isə elanları verilmişdir. Hazırda 5 müsabiqənin nəticələri əsasında qalib layihələr üzrə elmi-tədqiqat işləri aparılır, sonuncu 2 müsabiqə üzrə isə layihələr və sənədlər qəbul olunmaqdadır. Ümumilikdə qurum hazırda 151 qrant layihəsinin idarə olunması üzrə işləri yerinə yetirir. Bu sıradan artıq onlarca layihələr tamamlanmış, uğurlu nəticələr alınmış və "Science Citation İndex"li və yüksək "İmpact Factor"lu jurnallarda məqalələr dərc edilmiş, kitablar nəşr olunmuşdur. Başa çatmış layihələrə fond tərəfindən müfaviq sertifikatlar təqdim edilir. Bundan başqa, bir sıra uğurlu layihələr üzrə (xüsusilə də pilot layihələr, humanitar və ictimai elmlər sahəsindən olan layihələr üzrə) aralıq və ya tam hesabatlar bir qayda olaraq qurum&nbsp; tərəfindən keçirilən seminar və ya yüksək səviyyəli tədbirlər zamanı dinlənilir, KİV-də təbliğ olunur.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Elmin İnkişafı Fondu 2011-ci il noyabr ayında ilk dəfə olaraq "BakuTel-2011" sərgisində Dövlət Pavilyonunda uğurla təmsil olunmuş, təbliğat və təşviqat işləri aparılmışdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fondun maliyyələşdirdiyi layihələrin sayı ilbəil artır, format zənginləşir və müsabiqəyə təqdim olunan işlərin keyfiyyəti nəzərəçarpacaq dərəcədə yüksəlir. 2010-cu ilin 1-ci və 2-ci müsabiqəsi üzrə cəmi 44 layihə qalib olmuşdursa, 2010-cu illə müqayisədə 2011-ci ilin 1-ci müsabiqəsi üzrə qalib layihələrin sayı təqribən iki dəfə artaraq 82-yə çatmış, təkcə AMEA təşkilatlarının deyil, həmçinin universitetlərin, nazirliklər və digər qurumların nəzdində olan elmi-tədqiqat, qeyri-hökumət təşkilatlarının nümayəndələri də qaliblər sırasında olmuşlar.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">2011-ci ildə keçirilən müsabiqələrdən aydın oldu ki, fəal alimlər təbəqəsi fondun iş formasına və prinsiplərinə daha çox uyğunlaşıblar. İlk vaxtlarda, əsasən 2010-cu ildə müsabiqələrə və layihələrin yazılmasına qeyri-adekvat fikirlərlə yanaşanlar, başqa fondların öyrətdiyi "ərköyünlük" və qeyri-şəffaf üsullardan yararlanmaq istəyənlər var idi. Lakin zaman keçdikcə qurumun iş prinsipi və meyarları ilə tanış olan alimlər və digər insanlar öz fikirlərini dəyişdilər.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><strong>Fonda təqdim olunan layihələr aşağıdakı qrantlar şəklində dəstəklənir:</strong></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><em>- əhəmiyyətli və qısa zamanda dönüş yarada biləcək elmi-texniki nəticələrin alınması məqsədilə elmin ayrıca götürülmüş sahəsinin və ya istiqamətinin inkişafına böyükhəcmli qrantın verilməsi yolu ilə təşkilat tərəfindən təqdim edilən pilot layihəsinin maliyyələşdirilməsi (ən müasir elmi cihaz, avadanlıq, qurğular alınması, paralel olaraq bunlarda işləyə bilən kadrların xaricdə hazırlığı və s. kimi məsələlərin həlli);</em></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><em>- fizika-riyaziyyat və texnika elmləri, Yer haqqında elmlər, biologiya, tibb və aqrar elmləri, kimya elmləri, humanitar və ictimai elmlər sahələrini əhatə edən (elmi prioritetlər üzrə təqdim olunmuş layihələrə üstünlük verilməklə) fundamental və tətbiqi xarakterli layihələrin qrantlar vasitəsilə maliyyələşdirilməsi;</em></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><em>-&nbsp; axtarış-innovasiyayönlü layihələrin qrantlar vasitəsilə maliyyələşdirilməsi;</em></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><em>- cəmiyyətin sosial-mənəvi inkişafına xidmət edən, humanitar və ictimai elmlər sahəsində yerinə yetirilən elmi-tədqiqat işləri üzrə layihələrin məqsədli qrantlar vasitəsilə maliyyələşdirilməsi;</em></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><em>- xüsusi layihələrin qrantlar vasitəsilə maliyyələşdirilməsi: elmi-tədqiqatların müasir tələblərə cavab verən maddi-texniki təminatı; ölkənin sosial-mənəvi, elmi-texniki və iqtisadi inkişafı üçün xüsusi əhəmiyyət kəsb edən respublika, regional və beynəlxalq səviyyəli konfrans, simpozium, seminar və başqa elmi tədbirlərin Azərbaycan Respublikasında təşkili və keçirilməsi; Azərbaycan alimlərinin və mütəxəssislərinin xaricdə keçirilən nüfuzlu regional və beynəlxalq elmi tədbirlərdə iştirakının qismən və ya tam şəkildə maliyyələşdirilməklə təmin edilməsi; Azərbaycanda elmin inkişafı üçün mühüm əhəmiyyət kəsb edən elmi əsərlərin (monoqrafiya və atlasların, sifarişli əsasda yazılmış elmi və analitik icmalların, həmçinin elmin tədrisi ilə bağlı və elmi-kütləvi xarakterli əsərlərin) nəşrinin dəstəklənməsi; çeviklik tələb edən xüsusi elmi ekspedisiya və çöl işlərinin təşkili; zəruri hallarda (yeni metodun və cihazın öyrənilməsi və s.) qısamüddətli (bir ayadək) təcrübəkeçmə proqramlarının reallaşdırılması, Azərbaycanda elmin inkişafına, tədrisinə və təbliğinə yönəldilmiş digər tədbirlərin layihələr şəklində dəstəklənməsi.</em></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Aparılan müqayisəli təhlil göstərir ki, mövcud çatışmazlıqlardan biri də dünya elm məkanında Azərbaycan alimlərinin aldığı nəticələrin layiqincə öz təbliğini tapmamasıdır. Bu, çox mühüm və aktual məsələdir. İmkan yaradılmalıdır ki, elmi-tədqiqatların müxtəlif sahələrində Azərbaycanda alınmış elmi nəticələr dünya miqyasında müzakirələrə çıxarılsın, lazım gəldikdə elmi forumlarda "rəndələnsin", ən yaxşıları tanıdılsın, onlara elmi istinadlar verilsin. Alimlərimiz xaricdə keçirilən əhəmiyyətli konfranslarda, simpoziumlarda iştirak etsinlər, öz nəticələri barədə informasiya versinlər, əməkdaşlıq əlaqələri qursunlar, qısamüddətli təcrübə keçmək proqramlarından bəhrələnsinlər.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Elmin İnkişafı Fondunun cari və gələcək fəaliyyət planı zəngindir. Qurum bir çox əhəmiyyətli tədbirləri də müsabiqədənkənar olaraq, icraçı direksiyanın vəsaiti hesabına təşkil edərək keçirir. 2011-ci il 1-3 dekabr tarixlərində Bakıda "Baku Hilton" hotelində Azərbaycanın dövlət müstəqilliyinin bərpasının 20 illiyinə həsr olunmuş 3 günlük "Qafqaz Albaniyasının Azərbaycanın və Qafqazın tarixində yeri və rolu" adlı Beynəlxalq konfrans da bu uğurlu tədbirlərdəndir. Hər il 10 noyabr Ümumdünya Elm Günü yüksək səviyyədə qeyd olunur. Fondun icraçı direksiyasında keçirilən tədbirlərə tanınmış alimlər dəvət olunur.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Gələcək planlar sırasında yaxın illərdə Elm festivalının keçirilməsi, Bakıda Elm Muzeyinin yaradılması, elektron elmi-kütləvi jurnalın təsis olunması və nəşri, ən uğurlu layihələr üzrə yazılmış elmi və ya icmal xarakterli məqalələr toplusunun müntəzəm olaraq bir neçə dildə nəşri və dünya kitabxanalarına göndərilməsi kimi məsələlər durur.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fondun gələcəyə hesablanmış strategiyasına görə, uzun illərdən bəri istismarda olan, həm elmi, həm də fiziki cəhətdən köhnəlmiş cihazlar müasir tələblərə cavab verən ən yeni nəsil cihazlarla əvəz olunmalıdır. Müasir elmdə elə təcrübələr var ki, onları köhnəlmiş cihazlarda aparmaq mümkün deyil. Bu cihazlarda alınmış elmi nəticələr dünya miqyasında rəqabət apara da bilməz. Ona görə də yeni cihazlara ehtiyac şəksizdir. Əsas və çox ciddi məsələlərdən biri də bu cihazları idarə edərək onlar vasitəsilə ciddi elmi nəticələr ala biləcək yüksək ixtisaslı kadrların olmasıdır. Bu problemin yaranmaması üçün layihələr çərçivəsində yeni cihazları işlədə bilən kadrların hazırlanması üzərində də paralel olaraq iş gedir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fondun qrant müsabiqələri üzrə dövlət büdcəsindən maliyyə həcmi tədricən artır. 2010-cu ilin iki müsabiqəsi və 2011-ci ilin bir müsabiqəsi üzrə maliyyələşdirilmə həcmi müvafiq olaraq 6 milyon 050 min manat və 6 milyon 600 min manat olmuşdur. Fond dövlət büdcəsindən maliyyələşdirilir, lakin Nizamnamədə başqa mexanizmlər də nəzərdə tutulub, yəni yerli və xarici&nbsp; təşkilatlar tərəfindən də yardım ola bilər. İstisna deyil ki, fond öz işi ilə göstərilən etimadı doğrultsa, Azərbaycanda elmin inkişafında səmərəli rolunu sübut etmiş olsa, gələn illərdə maliyyələşdirilmə həcmi daha da artırıla bilər. Bu isə təkcə qurumun öz işini necə qurmasından yox, həm də alimlərin müsabiqədə hansı səviyyədə və dəyərli layihələrlə iştirak etməsindən çox asılıdır. Başqa sözlə, hər iki tərəfdən yüksək fəallıq olarsa, nəzərəçarpacaq irəliləyişlərə nail olmaq mümkündür. Burada təbliğat və təşviqat işlərinin aparılmasından da çox şey asılıdır. Ən böyük məqsəd Azərbaycanda elmin davamlı inkişafına nail olmaqdır. Lakin elmi nəticələri tanıtmadan və elmi təbliğ etmədən bu işi həyata keçirmək çətindir. Çünki ictimaiyyət elmi nəticələri bilməli, onu qəbul etməli, elm xadimlərini qiymətləndirməlidir. Bu halda alimlərin nüfuzu artar.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Elmin İnkişafı Fondunun qrant müsabiqələrində gender, yaş, milliyyət, elmi ad və dərəcə, işləyən və işsiz, təqaüdçü kimi məsələlərə görə fərq qoyulmur. Müsabiqələrdə elmlə məşğul olan, potensiallı və elmi tutumlu ideyaları həyata keçirməyə qadir olan ixtiyari Azərbaycan vətəndaşı iştirak edə bilər. 2011-ci il üçün qalib layihə rəhbərləri və icraçılarının statistikası göstərir ki, kişi-qadın nisbəti 58-42 faiz kimidir, 56-65 yaşarası layihə icraçıları çoxluq təşkil edir, gənclər isə (26-35 yaşarası) bu sırada üçüncü yerdədir. 3 pilot layihə (hər biri 1 milyon manatadək) biologiya, tibb və aqrar elmlərini, kimya elmlərini və Yer haqqında elmləri əhatə edir və maddi-texniki bazanın ən müasir səviyyədə yenilənməsini və paralel olaraq kadr hazırlığını nəzərdə tutur. Ümumiyyətlə, elmi cihazlar, avadanlıq və qurğuların Yaponiya, Almaniya, ABŞ və digər inkişaf etmiş ölkələrdən alınaraq quraşdırılması nəzərdə tutulmuşdur. Fundamental-tətbiqi və digər xarakterli layihələrin əksəriyyəti fizika-riyaziyyat və texnika elmləri sahəsindədir. 2010-cu ilin müsabiqələri üzrə AMEA-nın Fizika İnstitutunda reallaşdırılan birinci pilot layihəsi fondun ən böyük uğurlarındandır. Yüksək texnologiyalar üçün yeni materiallar və cihaz strukturları, nanotexnologiyalar sahəsində dünyanın elmi cihazlar istehsal edən qabaqcıl şirkətlərinin ən modern cihaz, qurğu və avadanlıqları alınaraq burada quraşdırılmış, ABŞ-da, Yaponiyada kadrların ixtisası artırılmışdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fondun müsabiqələrinin keçirilməsi qaydaları öz novatorluğu ilə seçilir və eyni zamanda, fundamental, tətbiqi və axtarış-innovasiya xarakterli elmi-tədqiqat layihələrinin və xüsusi proqramların idarə olunmasını nəzərdə tutur. Müsabiqələr üçün Elmin İnkişafı Fondunun elm sahələri və istiqamətlərinin təkmil Təsnifatı da hazırlanmışdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">2011-ci il Beynəlxalq Kimya ili olduğu üçün kimya üzrə daxil olan layihələrə üstünlük verilmişdir. 2011-ci il ölkəmizdə "Turizm ili" elan olunduğundan, turizm məqsədli arxeopark yaradılması ideyasını da özündə birləşdirən və Tovuz rayonu ərazisində yerləşən neolit dövrünə aid Göytəpə arxeoloji abidəsinin kompleks öyrənilməsinə fond tərəfindən müsabiqə yolu ilə 185 min manat qrant ayrılmışdır. 2012-ci ilin aprel ayında ölkə başçısı regionlara səfəri zamanı bu abidəni də ziyarət etmiş, görülən işləri qiymətləndirmişdir. Göytəpə Arxeoloji Parkının yaradılması haqqında Prezident sərəncam vermişdir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><strong>"Azərbaycan gəncliyi 2011-2015-ci illərdə" Dövlət Proqramının həyata keçirilməsi ilə əlaqədar 2011-ci il noyabrın 10-da Ümumdünya Elm Günündə - fond tərəfindən Gənc alim və mütəxəssislərin 1-ci müsabiqəsi (35 yaşa qədər olan alim və mütəxəssislərin iştirakı ilə) elan olunaraq keçirilmiş, müsabiqənin nəticələri isə 2012-ci il martın 20-də elan olunmuşdur. Ölkə tarixində ilk dəfə olaraq təşkil edilən Gənc alim və mütəxəssislərin 1-ci müsabiqəsinin ilk qalibləri ilə görüş isə 2012-ci il aprelin 12-də keçirilmişdir. Müsabiqədən əvvəl bir qrup gənc alim və mütəxəssislərlə Elmin İnkişafı Fondunun icraçı direksiyasında olan görüşün və müzakirələrin nəticələri müsabiqənin elmi prioritetlərinin təyinində və müsabiqə şərtlərinin müəyyənləşdirilməsində həlledici rol oynamışdır.</strong></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Gənc alim və mütəxəssislərin ilk qrant müsabiqəsi çərçivəsində 26 layihə qalib gəlmişdir. Bu layihələr üzrə ən müxtəlif qurumlardan 73 gənc alim və mütəxəssis müvəqqəti yaradıcı kollektivlər şəklində elmi-tədqiqatlarla məşğul olacaq və bir sıra elmi proqramlarını reallaşdıracaqlar. Müsabiqədə qalib gələn layihə rəhbərləri və icraçılar müxtəlif dövlət qurumlarını, ali təhsil müəssisələrini, qeyri-hökumət təşkilatlarını, özəl qurumları təmsil edirlər. Qalib layihələr sırasında 15 layihə fundamental-tətbiqi xarakterli, 2 layihə axtarış-innovasiya xarakterli, 2 layihə maddi-texniki təminat xarakterli, 5 layihə ekspedisiya və çöl işləri xarakterli, 1 layihə Azərbaycanda elmi tədbirin təşkili və keçirilməsi və 1 layihə xaricdə qısamüddətli təcrübəkeçmə xarakterli olmuşdur. Qalib layihələrin rəhbər və icraçıları Azərbaycan Milli Elmlər Akademiyasının 37 əsas institutundan 15-nin, 1 mərkəzin, 1 qeyri-hökumət təşkilatının, 1 özəl müəssisənin əməkdaşları, 8 ali təhsil müəssisəsinin (1-i özəl universitet olmaqla) tələbələri və əməkdaşlarıdırlar. 5 elm sahəsi üzrə 26 layihədən 5 layihə fizika-riyaziyyat və texnika elmləri üzrə, 3 layihə Yer haqqında elmlər üzrə, 9 layihə biologiya, tibb və aqrar elmləri üzrə, 4 layihə kimya elmləri, 5 humanitar və ictimai elmlər üzrədir. Müsabiqədə qalib layihələrin ümumi maliyyələşdirilmə həcmi 500000 manat təşkil etmişdir. 35 yaşadək olan layihə rəhbərləri və icraçıları arasında gender bərabərliyi müşahidə edilir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><strong>"Azərbaycan gəncliyi 2011-2015-ci illərdə" Dövlət Proqramı və bu proqramın həyata keçirilməsi üzrə Tədbirlər planının 6.3.1 bəndinə əsasən, Elmin İnkişafı Fondu tərəfindən Azərbaycanda çalışan ən fəal gənc alim və mütəxəssislər haqqında elektron məlumat bankı yaradılması üzrə işlərə başlanmış və ilkin versiya hazırlanmışdır.</strong></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Son iki ildə də dövlət başçısı tərəfindən elmin inkişafını təmin etmək sahəsində bir sıra digər strateji addımlar da atılmışdır. Prezident İlham Əliyevin "Azərbaycan Milli Elmlər Akademiyasının gənc alimlərinin Avropanın elmi mərkəzlərində doktorantura təhsilinin maliyyələşdirilməsi haqqında" 2010-cu il 9 fevral tarixli sərəncamı respublikada elmi-tədqiqatların müasir standartlar səviyyəsində aparılmasını, ölkənin elmi kadr potensialının artırılmasını və Azərbaycanda elmin beynəlxalq elm məkanına inteqrasiyasının təmin olunmasını daha da sürətləndirmək məqsədi daşıyır. Sərəncamla Azərbaycan Respublikasının 2010-cu il dövlət büdcəsində nəzərdə tutulmuş Azərbaycan Respublikası Prezidentinin Ehtiyat Fondundan Azərbaycan Milli Elmlər Akademiyasına gənc alimlərin Avropanın elmi mərkəzlərinin doktoranturalarında təhsil almaları üçün 500 min manat məbləğində vəsait ayrılmışdır. Bu, sosial-iqtisadi inkişafın keyfiyyətcə yeni mərhələsində elmi-tədqiqatların Avropa səviyyəsinə çatdırılmasını, gənc alimlərin dünya elminə inteqrasiyasını nəzərdə tutur.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Dövlət büdcəsindən elm xərclərinə ayrılan maliyyə həcmi ilbəil artırılır. 2012-ci ildə elm xərclərinə 123367974 manat (122797091 manat mərkəzləşdirilmiş və 570883 manat yerli xərclər olmaqla), 2011-ci illə (108720757 manat) müqayisədə 14647217 manat və yaxud 13,47 faiz çox vəsait ayrılmışdır. Həmin xərclər fundamental elmi-tədqiqatların və dövlət orqanlarında mövcud olan elmi-tədqiqat təşkilatları tərəfindən həyata keçirilən elmi işlərin maliyyələşməsinə yönəldiləcəkdir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">2012-ci ildə elm xərclərində elmi-tədqiqat layihələrinin Elmin İnkişafı Fondu vasitəsilə həyata keçirilməsi üçün qurumun saxlanma xərcləri də daxil olmaqla, 7034930 manat vəsait ayrılmışdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Fondun icraçı direksiyası etimadı doğrultmaq üçün bütün səylərini göstərir. Bu nüfuzlu elm qurumu artıq formalaşma və təşkilatlanma dövrünü başa vurmuş və fəaliyyətini genişləndirməkdədir.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Azərbaycan Milli Elmlər Akademiyasının 2011-ci il 26 aprel tarixdə keçirilən illik ümumi yığıncağında Prezident İlham Əliyev giriş nitqində qeyd etmişdir:</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;"><strong>"https://www.sdf.gov.az.2009-cu ildə Elmin İnkişafı üzrə Milli Strategiya və Dövlət Proqramı qəbul edilmişdir, ondan sonra Elmin İnkişafı Fondu yaradılmışdır. Bu fondun xətti ilə nəinki müasir avadanlığın alınması öz həllini tapır, eyni zamanda, müxtəlif qrantlar verilir ki, biz Azərbaycanda elmi araşdırmaları stimullaşdıraqhttps://www.sdf.gov.az."</strong></span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Prezident İlham Əliyev 2011-ci il 4 noyabr tarixli sərəncamına əsasən, Elmin İnkişafı Fondunun dəstəklənməsi, ölkədə elmi-tədqiqatların müasir standartlar səviyyəsində aparılmasını və xalqımızın mədəni-tarixi irsinin daha dərindən araşdırılmasını təmin etmək məqsədilə Elmin İnkişafı Fondu üçün Azərbaycan Respublikasının 2011-ci il dövlət büdcəsində nəzərdə tutulmuş Azərbaycan Respublikası Prezidentinin Ehtiyat Fondundan 3 milyon manat məbləğində vəsait ayrılmışdır.</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Prezident İlham Əliyevin sədrliyi ilə 2012-ci il 16 yanvar tarixdə Azərbaycan Respublikası Nazirlər Kabinetinin 2011-ci ilin sosial-iqtisadi inkişafının yekunlarına və 2012-ci ildə qarşıda duran vəzifələrə həsr olunmuş iclasındakı giriş nitqində dövlət başçısı demişdir: "https://www.sdf.gov.az.Qeyd etməliyəm ki, hazırda fəaliyyət göstərən Elmin İnkişafı Fondunun təcrübəsi də çox müsbətdir. Yəni, bu fondun xətti ilə müxtəlif proqramların icrasında, o cümlədən gənclər, gənc alimlər də çox fəal iştirak edirlər. Gənclər Fondu da fəaliyyətini bu səpkidə, yəni bu istiqamətdə aparmalıdırhttps://www.sdf.gov.az."</span></p>
                    <p style="text-align: justify;"><span style="color: #003366;">Elmin İnkişafı Fondunun ən ülvi məqsədi və vəzifəsi Azərbaycan xalqının, alimlərinin rifahına və ölkənin tərəqqisinə, dövlətin möhkəmləndirilməsinə, elmin yüksək xətlə inkişaf strategiyasının müəyyənləşdirilməsinə və təkmilləşdirilməsinə, Azərbaycan alimlərinin elmi-tədqiqat layihələrinin uğurla həyata keçirilməsinə və ölkədə elm sahəsində dünyamiqyaslı və rəqabət apara biləcək elmi nəticələrin alınmasının reallaşdırılmasına və bu nəticələrin tezliklə iqtisadiyyatda, həyatda öz tətbiqini tapmasına yüksək səviyyədə xidmət etməkdir.</span></p>
                    <p style="text-align: right;"><span style="color: #003366;"><em>Mənbə:&nbsp;<span style="text-decoration: underline;"><span style="text-decoration: underline;"><a href="http://www.azerbaijan-news.az/index.php?mod=3&amp;id=13108" target="_blank"><span style="text-decoration: underline; color: #003366;">Azərbaycan qəzeti</span></a></span></span></em></span></p>
                    <p style="text-align: right;">&nbsp;</p>                        <p></p>

                </div>
                <div id="social" style="padding: 4px;"><a href="https://www.facebook.com/sharer/sharer.php?u=https://www.sdf.gov.az/az//generic/menu/Detail/100/menu" target="_blank" style="margin-right:5px;"><img src="https://www.sdf.gov.az/development/img/icon/fb.jpg"></a><a href="https://twitter.com/intent/tweet?url=https://www.sdf.gov.az/az//generic/menu/Detail/100/menu" target="_blank" style="margin-right:5px;"><img src="https://www.sdf.gov.az/development/img/icon/tw.jpg"></a><a href="mailto:?subject=Yaranma tarixi&amp;body=https://www.sdf.gov.az/az//generic/menu/Detail/100/menu" style="margin-right:5px;"><img src="https://www.sdf.gov.az/development/img/icon/em.jpg"></a><a onclick="window.print()"><img src="https://www.sdf.gov.az/development/img/icon/pr.jpg"></a></div>
            </div>
            <div style="clear-both:"></div>
        </div>
    </div>
</div>